const Discord = require('discord.js');
require('dotenv').config();

const client = new Discord.Client();

client.on('ready', () => {
    console.log('Bot is ready');
});

client.login(process.env.BOT_TOKEN);

const backstory = [
    "It is the year 1349 DR, in the month of Deepwinter. You have been on the road for nearly two months now, and snow hangs thick on the trees as you make your way towards the town of Orlbar, at the foot of the Greypeak Mountains. The Greypeaks are known throughout Faerun for their silver and iron mines, but it is a different type of metal that brought you here: gold. While you were in Neverwinter you overheard rumours of a large horde of treasure within an abandoned goblin keep. Even tavern rumours prove to be fruitful sometimes, and having been without a purpose for some months, you departed immediately for the Grey Vale. When you reach Orlbar, the air is brisk and town is busy. Carts carry all manner of goods: timber, wool bales, grain, and animals from the surrounding country. Some of these goods would be bound for Waterdeep or Neverwinter, others for the nearby city of Loudwater. Hungry and thirsty after many days on the road, you enter the first tavern you see, The Woodsman’s Retreat, and satisfy your cravings. Bread, cheese and a hot mulled wine do the trick nicely. You then enquire from the barkeep about accomodation. Your bones ache and rest is essential. The mountains can wait one or two days while you rest and replenish your supplies in town. The barkeep tells you that a very respectable inn, the Silver Flask, is just nearby.",
    "Toting your backpack, you walk down the street to the Silver Flask and pay for a room. The inkeep is a jolly woman who is glad to have your business, and she lights a cosy fire in your room. You bathe, then lie down to rest and soon fall into a deep sleep; it’s been a while since your travel-hardened self has had clean sheets and a roof overhead! You are woken later that night by noise from the next room. You can hear a woman openly sobbing on the other side of the wall. The sound is gut-wrenching. Every now and then a male voice says something, as if trying to comfort her. You tolerate this for a while, but eventually it becomes evident that sleep is going to be impossible, and you walk out into the hallway and knock on the door to the room next to yours. An elderly man answers. He is dressed finely, like a member of the aristocracy, but sports a nasty black eye and a gash across his cheek. In the background a woman, also richly dressed, sits on a chair by the fire, her face buried in her hands. “Yes? What is it?” the elderly gentleman asks directly. You straighten yourself up, peering into the room. “I was wondering what all the noise was about,” you say, although now you don’t feel quite so annoyed. “I could hear the crying from next door. I was wondering,” you say gruffly, not used to dealing with aristocrats, “If it’s anything I can help you with? Perhaps then we can all get some rest?” At this the woman looks up and sees you. You probably look a fright, after all those weeks on the road – ungroomed, hair dishevelled, travel-worn clothes - but you’ve had a bath so you at least you don’t smell bad. However, your type has an… air about them. You’ve seen a fight or two and know how to handle yourself in most situations. You’re what’s known in these parts as ‘the adventuring type.’ Such types generally know how to get things done, things that others might shy away from. “Show our guest in, Elric,” the woman says weakly, drying her tears with a silk handkerchief.",
    "You are shown to a chair. For some reason, this old couple, who introduce themselves as Lord and Lady Brewmont, welcome your presence, if only as a distraction from the grief they seem consumed by. “We arrived here last night,” Lady Brewmont begins. “Elric is so busy these days, so we thought we would bring ourselves out to Orlbar for a little holiday. Our son, he’s so fond of the mountains. Loves all the stories. Well, he’s our grandson really. The son of our daughter who died some years ago. He is all we have left of her. We call him our son.“ Lady Brewmont begins sobbing once more. Elric Brewmont picks up the thread. “Long story short, my friend, we were accosted on the highway. We were passing along a lonely stretch of read when he appeared, from nowhere. A knight, a towering brute of a man, all clad in armour.” Lord Elric points to his face. “Did this to me, knocked me out cold. Then he grabbed our boy, threw him on a horse and bolted! Without a word!” “Hmm,” you say, mulling over this information. “Did he seem familiar, this knight?” Elric shakes his head. “I know what you’re thinking. Wealthy aristocrat, on holiday from Loudwater, someone must have known we were coming out here, and siezed the opportunity. It’s true, I am what you would call… a public figure. It is well known, in Loudwater at least, that I am a wealthy man. But no…. this knight was something else. We didn’t see his face, it was hidden by a great metal visor. A towering warrior he was, a hulk of a man.” Lady Brewmont speaks again. “And he has kidnapped our poor little Darek! Abducted him, just ripped him out of our grasp!”",
    "“What did you do then?” you ask. “We came straight to Orlbar,” Lady Brewmont says. “We went to the Captain of the Guard, but he, he…” “A thoroughly incompetent fool,” Lord Brewmont growls. “Said this Knight was a ghost, that he’d chosen Darek as his squire, and that there was nothing we could do about it! Said Darek wasn’t the first. Called him The Death Knight! You can imagine what a comfort that was to us.” “They say the Knight lives in the wood nearby,” Lady Brewmont says airily, as if in a waking dream. “Weathercote Wood, isn’t it dear?” The old man grits his teeth, staring into the fire, and punches his palm. “Ghost my arse!” he snarls through gritted teeth. “That knight looked real enough to me. He’s a lunatic, nothing more, a lunatic who kidnaps young boys! And when I find the blaggard, by the Gods will he pay!” You can’t help thinking that Lord Brewmont is a bit out of his depth here. You don’t doubt his resolve, but he looks as though his days of conquest are well behind him. You feel for this poor old couple. While not usually associating with the wealthy, you do know that you have something to offer them, and you’re never one to shy away from a good adventure… especially when the chance of a reward is on the table. “I can find your boy,” you hear yourself saying. The woman looks up, and new hope begins to shine from her eyes. “Oh Gods,” she says, her voice quavering. “We’ll give you anything, anything…” The old man is a little more practical. “If I was a few decades younger, I’d be out there myself. I saw action in the Battle of Tanglefork, when we freed the Vale from Rensha rule.” You nod appreciatively – that battle happened about 30 years ago, and was said to be fierce. You are not surprised – Elric Brewmont definitely carries himself like an old veteran. “I can’t put my sword forward any more, but I can offer you gold, my friend… 2000 pieces of it, to be exact…”"
];

client.on('message', (msg) => {
    if (msg.content === 'Hello') msg.reply('Hi');

    if (msg.content === '?backstory') {
        for (var i = 0; i < backstory.length; i++) {
            msg.channel.send(backstory[i]);
        }
    }
});